#!/usr/bin/python3

try:
    from diffted import entry_point
except ImportError:
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'lib')))
    from diffted import entry_point

if __name__ == '__main__':
    entry_point()

